#ifndef WORLD_CONSTANTS_H
#define WORLD_CONSTANTS_H

#define CHUNK_WIDTH 16
#define REGION_WIDTH 32
#define CHUNK_HEIGHT 256
#define CHUNK_SIZE CHUNK_WIDTH * CHUNK_WIDTH * CHUNK_HEIGHT


typedef enum  {
    BLOCK_AIR = 0,
    BLOCK_STONE = 1,
    BLOCK_GRASS = 2,
    BLOCK_BEDROCK = 7,
    BLOCK_GOLD_ORE = 14,
    BLOCK_IRON_ORE = 15,
    BLOCK_COAL_ORE = 16,
    BLOCK_DIAMOND_ORE = 56,
    BLOCK_CRAFTING_TABLE = 58
} BlockType;

#endif
